import { Poppins, Open_Sans } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400"],
});

const opensans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: "variable",
});

export const metadata = {
  title: "My first next app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${opensans.className} `}>
        <div className="wrapper">
          {/* <div className="row">
            <h1>Global Header</h1>
          </div> */}
          {children}
          {/* <div className="row">
            <h1>Global Footer</h1>
          </div> */}
        </div>
      </body>
    </html>
  );
}
